version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
  groups:
    cargo-minor-patch:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
  ignore:
  - dependency-name: git2
    versions:
    - 0.13.17
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Berlin
