[mappings]
"INI" = [
        "${XDG_DATA_HOME}/konsole/*.{colorscheme,profile}",
    "${HOME}/.local/share/konsole/*.{colorscheme,profile}",

    "QtProject.conf",
    "Trolltech.conf",

    "akonadi_*[0-9]rc",

    "kcmfonts",
    "kdeglobals",
    "knfsshare",
    "konsolesshconfig",

    # rc
    "baloofileinformationrc",
    "baloofilerc",
    "bluedevilglobalrc",
    "dolphinrc",
    "gwenviewrc",
    "kactivitymanagerd-pluginsrc",
    "kactivitymanagerd-statsrc",
    "kactivitymanagerdrc",
    "kaddressbookrc",
    "kalarmrc",
    "kalendaracrc",
    "kalendarrc",
    "kamosorc",
    "kate-externaltoolspluginrc",
    "katerc",
    "katevirc",
    "kbreakoutrc",
    "kcharselectrc",
    "kcminputrc",
    "kconf_updaterc",
    "kded5rc",
    "kded6rc",
    "keditbookmarksrc",
    "kexirc",
    "kgammarc",
    "kglobalshortcutsrc",
    "kgoldrunnerrc",
    "khelpcenterrc",
    "khotkeysrc",
    "kiorc",
    "kleopatrarc",
    "klipperrc",
    "kmagrc",
    "kmenueditrc",
    "kmixctrlrc",
    "kmixrc",
    "knighttimerc",
    "konquerorrc",
    "konsolerc",
    "korganizerrc",
    "kprivacyrc",
    "krenamerc",
    "krulerrc",
    "krunnerrc",
    "kscreenlockerrc",
    "kservicemenurc",
    "ksmserverrc",
    "ksplashrc",
    "kteatimerc",
    "ktimezonedrc",
    "ktouch2rc",
    "ktrashrc",
    "kwalletmanagerrc",
    "kwalletrc",
    "kwinrc",
    "kwinrulesrc",
    "kwriterc",
    "kxkbrc",
    "powerdevilrc",
    "powermanagementprofilesrc",
    "spectaclerc",

    # metainfos
    "katemetainfos",
    "kwritemetainfos",

    # plasma
    "plasma-localerc",
    "plasma-nm",
    "plasma-org.kde.plasma.desktop-appletsrc",
    "plasmashellrc",
]

JSON = [
    # Not INI files
        "${XDG_DATA_HOME}/drkonqi/crashes/*.ini",
    "${HOME}/.local/share/drkonqi/crashes/*.ini",
]
