[38;2;255;255;255m<?[0m[38;2;249;38;114mxml[0m[38;2;248;248;242m [0m[38;2;166;226;46mversion[0m[38;2;248;248;242m=[0m[38;2;230;219;116m"[0m[38;2;230;219;116m1.0[0m[38;2;230;219;116m"[0m[38;2;248;248;242m [0m[38;2;166;226;46mencoding[0m[38;2;248;248;242m=[0m[38;2;230;219;116m"[0m[38;2;230;219;116mUTF-8[0m[38;2;230;219;116m"[0m[38;2;255;255;255m?>[0m
[38;2;117;113;94m<!--[0m[38;2;117;113;94m External document type definition [0m[38;2;117;113;94m-->[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mENTITY[0m[38;2;248;248;242m [0m[38;2;248;248;242m%[0m[38;2;248;248;242m [0m[38;2;255;255;255midentifier[0m[38;2;248;248;242m [0m[38;2;230;219;116m"[0m[38;2;230;219;116mID #REQUIRED[0m[38;2;230;219;116m"[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mENTITY[0m[38;2;248;248;242m [0m[38;2;255;255;255mpublisher[0m[38;2;248;248;242m [0m[38;2;230;219;116m"[0m[38;2;230;219;116mExample [0m[38;2;190;132;255m&[0m[38;2;190;132;255mamp[0m[38;2;190;132;255m;[0m[38;2;230;219;116m Company[0m[38;2;230;219;116m"[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mENTITY[0m[38;2;248;248;242m [0m[38;2;255;255;255mcopyright[0m[38;2;248;248;242m [0m[38;2;230;219;116m"[0m[38;2;190;132;255m&#[0m[38;2;190;132;255m169[0m[38;2;190;132;255m;[0m[38;2;230;219;116m 2026[0m[38;2;230;219;116m"[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mNOTATION[0m[38;2;248;248;242m [0m[38;2;255;255;255mpng[0m[38;2;248;248;242m [0m[3;38;2;102;217;239mSYSTEM[0m[38;2;248;248;242m [0m[38;2;230;219;116m"[0m[38;2;230;219;116mimage/png[0m[38;2;230;219;116m"[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mENTITY[0m[38;2;248;248;242m [0m[38;2;255;255;255mlogo[0m[38;2;248;248;242m [0m[3;38;2;102;217;239mSYSTEM[0m[38;2;248;248;242m [0m[38;2;230;219;116m"[0m[38;2;230;219;116mlogo.png[0m[38;2;230;219;116m"[0m[38;2;248;248;242m [0m[3;38;2;102;217;239mNDATA[0m[38;2;248;248;242m [0m[38;2;230;219;116mpng[0m[38;2;255;255;255m>[0m

[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255mcatalog[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;230;219;116mbook[0m[38;2;249;38;114m+[0m[38;2;255;255;255m)[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255mbook[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;230;219;116mtitle[0m[38;2;248;248;242m,[0m[38;2;248;248;242m [0m[38;2;230;219;116mauthor[0m[38;2;249;38;114m+[0m[38;2;248;248;242m,[0m[38;2;248;248;242m [0m[38;2;230;219;116mdescription[0m[38;2;249;38;114m?[0m[38;2;255;255;255m)[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mATTLIST[0m[38;2;248;248;242m [0m[38;2;255;255;255mbook[0m
[38;2;248;248;242m    [0m[38;2;166;226;46mid[0m[38;2;248;248;242m [0m[3;38;2;253;151;31m%[0m[3;38;2;253;151;31midentifier[0m[3;38;2;253;151;31m;[0m
[38;2;248;248;242m    [0m[38;2;166;226;46mformat[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;230;219;116mpaper[0m[38;2;248;248;242m|[0m[38;2;230;219;116mdigital[0m[38;2;255;255;255m)[0m[38;2;248;248;242m [0m[38;2;230;219;116m"[0m[38;2;230;219;116mpaper[0m[38;2;230;219;116m"[0m
[38;2;248;248;242m    [0m[38;2;166;226;46mlanguage[0m[38;2;248;248;242m [0m[3;38;2;102;217;239mCDATA[0m[38;2;248;248;242m [0m[38;2;249;38;114m#[0m[38;2;249;38;114mIMPLIED[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255mtitle[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;190;132;255m#[0m[38;2;190;132;255mPCDATA[0m[38;2;255;255;255m)[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255mauthor[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;190;132;255m#[0m[38;2;190;132;255mPCDATA[0m[38;2;255;255;255m)[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255mdescription[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;190;132;255m#[0m[38;2;190;132;255mPCDATA[0m[38;2;248;248;242m|[0m[38;2;230;219;116memphasis[0m[38;2;255;255;255m)[0m[38;2;249;38;114m*[0m[38;2;255;255;255m>[0m
[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255memphasis[0m[38;2;248;248;242m [0m[38;2;255;255;255m([0m[38;2;190;132;255m#[0m[38;2;190;132;255mPCDATA[0m[38;2;255;255;255m)[0m[38;2;255;255;255m>[0m

[38;2;255;255;255m<![[0m[38;2;255;255;255mINCLUDE[0m[38;2;248;248;242m[[0m
[38;2;248;248;242m  [0m[38;2;255;255;255m<![0m[38;2;249;38;114mELEMENT[0m[38;2;248;248;242m [0m[38;2;255;255;255mappendix[0m[38;2;248;248;242m [0m[38;2;190;132;255mANY[0m[38;2;255;255;255m>[0m
[38;2;248;248;242m][0m[38;2;255;255;255m]>[0m
